; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "FillingOutForms(win7)"
#define MyAppVersion "0.0.2"
#define MyAppExeName "FillingOutForms.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{292AEB0D-B4F6-46D1-972C-9E32D70FA40F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\nrd\Desktop
OutputBaseFilename=FillingOutFormsSetup(win7)
SetupIconFile=C:\Users\nrd\Desktop\ProjectQT\FillingOutForms\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\addf.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\fill.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\libgcc_s_dw2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\libGLESV2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\main.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\meny.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\metaINF_res.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\moc_addf.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\moc_addf.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\moc_fill.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\moc_fill.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\moc_meny.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\moc_meny.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\moc_predefs.h"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\qrc_res.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\qrc_res.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\Qt5PrintSupport.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\Qt5Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\iconengines\*"; DestDir: "{app}\iconengines"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\imageformats\*"; DestDir: "{app}\imageformats"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\platforms\*"; DestDir: "{app}\platforms"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\printsupport\*"; DestDir: "{app}\printsupport"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\styles\*"; DestDir: "{app}\styles"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\translations\*"; DestDir: "{app}\translations"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\nrd\Desktop\build-FillingOutForms-Desktop_Qt_5_12_12_MinGW_32_bit-Release\release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Заполнение форм"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

